# CDC Pipeline — Single Container
# Kafka runs in Redpanda Cloud

networks:
  cdc-network:
    driver: bridge

services:

  kafka-connect:
    image: debezium/connect:2.4
    container_name: cdc-kafka-connect
    networks:
      - cdc-network
    ports:
      - "8083:8083"
    environment:
      # Point to Redpanda Cloud instead of local Kafka
      BOOTSTRAP_SERVERS: "d7ect2ugq0q78n6tk3cg.any.ap-south-1.mpx.prd.cloud.redpanda.com:9092"

      GROUP_ID: cdc-connect-group
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: "3"
      OFFSET_STORAGE_REPLICATION_FACTOR: "3"
      STATUS_STORAGE_REPLICATION_FACTOR: "3"

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "3"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "3"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "3"

      # SASL/SSL auth for Redpanda Cloud
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_MECHANISM: SCRAM-SHA-256
      CONNECT_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="debezium-user" password="debezium2026";'

      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_PRODUCER_SASL_MECHANISM: SCRAM-SHA-256
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="debezium-user" password="debezium2026";'

      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_CONSUMER_SASL_MECHANISM: SCRAM-SHA-256
      CONNECT_CONSUMER_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="debezium-user" password="debezium2026";'

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      KAFKA_HEAP_OPTS: "-Xmx768m -Xms384m"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    deploy:
      resources:
        limits:
          memory: 1000m
    restart: unless-stopped